/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Logica.Vehiculo;
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author sala104
 */
public class Principal extends javax.swing.JFrame {
    
        LinkedList<Vehiculo> vehiculo = new LinkedList<Vehiculo>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_conductor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ruta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        pnl_registrar = new javax.swing.JPanel();
        btn_registrar = new javax.swing.JButton();
        pnl_consultar = new javax.swing.JPanel();
        btn_consultar = new javax.swing.JButton();
        pnl_limpiar = new javax.swing.JPanel();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 58, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transportes LTDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, 50));

        txt_descripcion.setBackground(new java.awt.Color(39, 58, 45));
        txt_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        txt_descripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 480, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Placa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(39, 58, 45));
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 480, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripcion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        txt_placa.setBackground(new java.awt.Color(39, 58, 45));
        txt_placa.setForeground(new java.awt.Color(255, 255, 255));
        txt_placa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_placaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 480, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Conductor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txt_conductor.setBackground(new java.awt.Color(39, 58, 45));
        txt_conductor.setForeground(new java.awt.Color(255, 255, 255));
        txt_conductor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_conductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_conductorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 480, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ruta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        txt_ruta.setBackground(new java.awt.Color(39, 58, 45));
        txt_ruta.setForeground(new java.awt.Color(255, 255, 255));
        txt_ruta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 480, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Marca");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modelo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        txt_marca.setBackground(new java.awt.Color(39, 58, 45));
        txt_marca.setForeground(new java.awt.Color(255, 255, 255));
        txt_marca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marcaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 480, 40));

        txt_modelo.setBackground(new java.awt.Color(39, 58, 45));
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modeloActionPerformed(evt);
            }
        });
        jPanel1.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 480, 40));

        pnl_registrar.setBackground(new java.awt.Color(39, 58, 45));
        pnl_registrar.setLayout(new java.awt.BorderLayout());

        btn_registrar.setBackground(new java.awt.Color(39, 58, 45));
        btn_registrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_registrar.setContentAreaFilled(false);
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.setFocusPainted(false);
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        pnl_registrar.add(btn_registrar, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnl_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 260, 60));

        pnl_consultar.setBackground(new java.awt.Color(39, 58, 45));
        pnl_consultar.setLayout(new java.awt.BorderLayout());

        btn_consultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar.setText("Consultar");
        btn_consultar.setToolTipText("");
        btn_consultar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_consultar.setContentAreaFilled(false);
        btn_consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_consultar.setFocusPainted(false);
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_consultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_consultarMouseExited(evt);
            }
        });
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        pnl_consultar.add(btn_consultar, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnl_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 260, 60));

        pnl_limpiar.setBackground(new java.awt.Color(39, 58, 45));
        pnl_limpiar.setLayout(new java.awt.BorderLayout());

        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_limpiar.setContentAreaFilled(false);
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpiar.setFocusPainted(false);
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseExited(evt);
            }
        });
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        pnl_limpiar.add(btn_limpiar, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnl_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 260, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_placaActionPerformed

    private void txt_conductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_conductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_conductorActionPerformed

    private void txt_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutaActionPerformed

    private void txt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaActionPerformed

    private void txt_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modeloActionPerformed

    
     private void fnt_registrar(String placa, String nombre, String conductor, String ruta, String marca, String modelo, String descripsion){
        boolean identificacionRepetida = false;
        
        for(Vehiculo empleadoRepetido : vehiculo){
            if(empleadoRepetido.getPlaca().equals(placa)){
                identificacionRepetida = true;
                break;
            }
        }
        
        if(identificacionRepetida){
            JOptionPane.showMessageDialog(null, "El numero de placa ya esta registrado","ERROR" ,JOptionPane.ERROR_MESSAGE);           
        }else if(placa.isEmpty() || nombre.isEmpty() || conductor.isEmpty() || ruta.isEmpty() || marca.isEmpty() || modelo.isEmpty() || descripsion.isEmpty()){
        JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
        vehiculo.add(new Vehiculo(placa,nombre,conductor,ruta,marca,modelo,descripsion));
        JOptionPane.showMessageDialog(null, "Registrado correctamente" , "Registro", JOptionPane.PLAIN_MESSAGE);  
        fnt_limpiar();
        }
        
    }
    
    
    
    
    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
                fnt_registrar(txt_placa.getText(),
                      txt_nombre.getText(),
                      txt_conductor.getText(),
                      txt_ruta.getText(),
                      txt_marca.getText(),
                      txt_modelo.getText(),
                      txt_descripcion.getText());
    }//GEN-LAST:event_btn_registrarActionPerformed

    
     private void fnt_limpiar(){
        
        txt_placa.setText("");
        txt_nombre.setText("");
        txt_conductor.setText("");
        txt_ruta.setText("");
        txt_descripcion.setText("");
        txt_marca.setText("");
        txt_modelo.setText("");
    }
    
    
    
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered
        pnl_registrar.setBackground(new Color(255,255,255));
        btn_registrar.setForeground(new Color(39,58,45));
    }//GEN-LAST:event_btn_registrarMouseEntered

    private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited
        pnl_registrar.setBackground(new Color(39,58,45));
        btn_registrar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_registrarMouseExited

    
     private Vehiculo buscar_vehiculo(String placa){
        for(Vehiculo placaVehiculo : vehiculo){
           if(placaVehiculo.getPlaca().equals(placa))
               return placaVehiculo;
        }
        return null;
    }
    
    private void fnt_consultarEmpleado(String placa){
        Vehiculo placaVehiculo = buscar_vehiculo(placa);
        
        if(placaVehiculo != null){
            txt_nombre.setText(placaVehiculo.getNombre());
            txt_conductor.setText(placaVehiculo.getConductor());
            txt_ruta.setText(placaVehiculo.getRuta());
            txt_marca.setText(placaVehiculo.getMarca());
            txt_modelo.setText(placaVehiculo.getModelo());
            txt_descripcion.setText(placaVehiculo.getDescripsion()); 
        }
        else{
            JOptionPane.showMessageDialog(null, "No se encontro ningun vehiculo con ese numero de Placa", "ERROR" ,JOptionPane.ERROR_MESSAGE);
        }
    }    
    
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        fnt_consultarEmpleado(txt_placa.getText());
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_consultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseEntered
        pnl_consultar.setBackground(new Color(255,255,255));
        btn_consultar.setForeground(new Color(39,58,45));
    }//GEN-LAST:event_btn_consultarMouseEntered

    private void btn_consultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseExited
        pnl_consultar.setBackground(new Color(39,58,45));
        btn_consultar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_consultarMouseExited

    private void btn_limpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseEntered
        pnl_limpiar.setBackground(new Color(255,255,255));
        btn_limpiar.setForeground(new Color(39,58,45));
    }//GEN-LAST:event_btn_limpiarMouseEntered

    private void btn_limpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseExited
        pnl_limpiar.setBackground(new Color(39,58,45));
        btn_limpiar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_limpiarMouseExited

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_consultar;
    private javax.swing.JPanel pnl_limpiar;
    private javax.swing.JPanel pnl_registrar;
    private javax.swing.JTextField txt_conductor;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
